// Generated by gencpp from file serialtoros/graph_imgRequest.msg
// DO NOT EDIT!


#ifndef SERIALTOROS_MESSAGE_GRAPH_IMGREQUEST_H
#define SERIALTOROS_MESSAGE_GRAPH_IMGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serialtoros
{
template <class ContainerAllocator>
struct graph_imgRequest_
{
  typedef graph_imgRequest_<ContainerAllocator> Type;

  graph_imgRequest_()
    : req(false)  {
    }
  graph_imgRequest_(const ContainerAllocator& _alloc)
    : req(false)  {
  (void)_alloc;
    }



   typedef uint8_t _req_type;
  _req_type req;





  typedef boost::shared_ptr< ::serialtoros::graph_imgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serialtoros::graph_imgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct graph_imgRequest_

typedef ::serialtoros::graph_imgRequest_<std::allocator<void> > graph_imgRequest;

typedef boost::shared_ptr< ::serialtoros::graph_imgRequest > graph_imgRequestPtr;
typedef boost::shared_ptr< ::serialtoros::graph_imgRequest const> graph_imgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serialtoros::graph_imgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serialtoros::graph_imgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serialtoros::graph_imgRequest_<ContainerAllocator1> & lhs, const ::serialtoros::graph_imgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.req == rhs.req;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serialtoros::graph_imgRequest_<ContainerAllocator1> & lhs, const ::serialtoros::graph_imgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serialtoros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serialtoros::graph_imgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serialtoros::graph_imgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serialtoros::graph_imgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serialtoros::graph_imgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serialtoros::graph_imgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serialtoros::graph_imgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serialtoros::graph_imgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be3c44e19d0c6b00b25e356c69155e2a";
  }

  static const char* value(const ::serialtoros::graph_imgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe3c44e19d0c6b00ULL;
  static const uint64_t static_value2 = 0xb25e356c69155e2aULL;
};

template<class ContainerAllocator>
struct DataType< ::serialtoros::graph_imgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serialtoros/graph_imgRequest";
  }

  static const char* value(const ::serialtoros::graph_imgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serialtoros::graph_imgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool req\n"
;
  }

  static const char* value(const ::serialtoros::graph_imgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serialtoros::graph_imgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graph_imgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serialtoros::graph_imgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serialtoros::graph_imgRequest_<ContainerAllocator>& v)
  {
    s << indent << "req: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIALTOROS_MESSAGE_GRAPH_IMGREQUEST_H
