// Generated by gencpp from file serialtoros/GraphPath.msg
// DO NOT EDIT!


#ifndef SERIALTOROS_MESSAGE_GRAPHPATH_H
#define SERIALTOROS_MESSAGE_GRAPHPATH_H

#include <ros/service_traits.h>


#include <serialtoros/GraphPathRequest.h>
#include <serialtoros/GraphPathResponse.h>


namespace serialtoros
{

struct GraphPath
{

typedef GraphPathRequest Request;
typedef GraphPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraphPath
} // namespace serialtoros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serialtoros::GraphPath > {
  static const char* value()
  {
    return "ed9917bdabd17e90425e5793841d983a";
  }

  static const char* value(const ::serialtoros::GraphPath&) { return value(); }
};

template<>
struct DataType< ::serialtoros::GraphPath > {
  static const char* value()
  {
    return "serialtoros/GraphPath";
  }

  static const char* value(const ::serialtoros::GraphPath&) { return value(); }
};


// service_traits::MD5Sum< ::serialtoros::GraphPathRequest> should match
// service_traits::MD5Sum< ::serialtoros::GraphPath >
template<>
struct MD5Sum< ::serialtoros::GraphPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serialtoros::GraphPath >::value();
  }
  static const char* value(const ::serialtoros::GraphPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serialtoros::GraphPathRequest> should match
// service_traits::DataType< ::serialtoros::GraphPath >
template<>
struct DataType< ::serialtoros::GraphPathRequest>
{
  static const char* value()
  {
    return DataType< ::serialtoros::GraphPath >::value();
  }
  static const char* value(const ::serialtoros::GraphPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serialtoros::GraphPathResponse> should match
// service_traits::MD5Sum< ::serialtoros::GraphPath >
template<>
struct MD5Sum< ::serialtoros::GraphPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serialtoros::GraphPath >::value();
  }
  static const char* value(const ::serialtoros::GraphPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serialtoros::GraphPathResponse> should match
// service_traits::DataType< ::serialtoros::GraphPath >
template<>
struct DataType< ::serialtoros::GraphPathResponse>
{
  static const char* value()
  {
    return DataType< ::serialtoros::GraphPath >::value();
  }
  static const char* value(const ::serialtoros::GraphPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIALTOROS_MESSAGE_GRAPHPATH_H
