// Generated by gencpp from file serialtoros/graph_pathResponse.msg
// DO NOT EDIT!


#ifndef SERIALTOROS_MESSAGE_GRAPH_PATHRESPONSE_H
#define SERIALTOROS_MESSAGE_GRAPH_PATHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serialtoros
{
template <class ContainerAllocator>
struct graph_pathResponse_
{
  typedef graph_pathResponse_<ContainerAllocator> Type;

  graph_pathResponse_()
    : path()  {
    }
  graph_pathResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::serialtoros::graph_pathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serialtoros::graph_pathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct graph_pathResponse_

typedef ::serialtoros::graph_pathResponse_<std::allocator<void> > graph_pathResponse;

typedef boost::shared_ptr< ::serialtoros::graph_pathResponse > graph_pathResponsePtr;
typedef boost::shared_ptr< ::serialtoros::graph_pathResponse const> graph_pathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serialtoros::graph_pathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serialtoros::graph_pathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serialtoros::graph_pathResponse_<ContainerAllocator1> & lhs, const ::serialtoros::graph_pathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serialtoros::graph_pathResponse_<ContainerAllocator1> & lhs, const ::serialtoros::graph_pathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serialtoros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serialtoros::graph_pathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serialtoros::graph_pathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serialtoros::graph_pathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serialtoros::graph_pathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serialtoros::graph_pathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serialtoros::graph_pathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serialtoros::graph_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::serialtoros::graph_pathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d00cd540af97efeULL;
  static const uint64_t static_value2 = 0xb6b1589112fab63eULL;
};

template<class ContainerAllocator>
struct DataType< ::serialtoros::graph_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serialtoros/graph_pathResponse";
  }

  static const char* value(const ::serialtoros::graph_pathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serialtoros::graph_pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path\n"
"\n"
;
  }

  static const char* value(const ::serialtoros::graph_pathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serialtoros::graph_pathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graph_pathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serialtoros::graph_pathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serialtoros::graph_pathResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIALTOROS_MESSAGE_GRAPH_PATHRESPONSE_H
