// Generated by gencpp from file octo_qt/cam_array.msg
// DO NOT EDIT!


#ifndef OCTO_QT_MESSAGE_CAM_ARRAY_H
#define OCTO_QT_MESSAGE_CAM_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace octo_qt
{
template <class ContainerAllocator>
struct cam_array_
{
  typedef cam_array_<ContainerAllocator> Type;

  cam_array_()
    : data()  {
      data.assign(0);
  }
  cam_array_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef boost::array<int8_t, 2>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::octo_qt::cam_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::octo_qt::cam_array_<ContainerAllocator> const> ConstPtr;

}; // struct cam_array_

typedef ::octo_qt::cam_array_<std::allocator<void> > cam_array;

typedef boost::shared_ptr< ::octo_qt::cam_array > cam_arrayPtr;
typedef boost::shared_ptr< ::octo_qt::cam_array const> cam_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::octo_qt::cam_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::octo_qt::cam_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::octo_qt::cam_array_<ContainerAllocator1> & lhs, const ::octo_qt::cam_array_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::octo_qt::cam_array_<ContainerAllocator1> & lhs, const ::octo_qt::cam_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace octo_qt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::octo_qt::cam_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::octo_qt::cam_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::octo_qt::cam_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::octo_qt::cam_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::octo_qt::cam_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::octo_qt::cam_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::octo_qt::cam_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c07040a674f8e0c82e1935480c7f1f6";
  }

  static const char* value(const ::octo_qt::cam_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c07040a674f8e0cULL;
  static const uint64_t static_value2 = 0x82e1935480c7f1f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::octo_qt::cam_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "octo_qt/cam_array";
  }

  static const char* value(const ::octo_qt::cam_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::octo_qt::cam_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[2] data\n"
;
  }

  static const char* value(const ::octo_qt::cam_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::octo_qt::cam_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cam_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::octo_qt::cam_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::octo_qt::cam_array_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCTO_QT_MESSAGE_CAM_ARRAY_H
