// Generated by gencpp from file octo_qt/motor_status.msg
// DO NOT EDIT!


#ifndef OCTO_QT_MESSAGE_MOTOR_STATUS_H
#define OCTO_QT_MESSAGE_MOTOR_STATUS_H

#include <ros/service_traits.h>


#include <octo_qt/motor_statusRequest.h>
#include <octo_qt/motor_statusResponse.h>


namespace octo_qt
{

struct motor_status
{

typedef motor_statusRequest Request;
typedef motor_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motor_status
} // namespace octo_qt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::octo_qt::motor_status > {
  static const char* value()
  {
    return "ecef0d862731650eac828889c4228965";
  }

  static const char* value(const ::octo_qt::motor_status&) { return value(); }
};

template<>
struct DataType< ::octo_qt::motor_status > {
  static const char* value()
  {
    return "octo_qt/motor_status";
  }

  static const char* value(const ::octo_qt::motor_status&) { return value(); }
};


// service_traits::MD5Sum< ::octo_qt::motor_statusRequest> should match
// service_traits::MD5Sum< ::octo_qt::motor_status >
template<>
struct MD5Sum< ::octo_qt::motor_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::octo_qt::motor_status >::value();
  }
  static const char* value(const ::octo_qt::motor_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::octo_qt::motor_statusRequest> should match
// service_traits::DataType< ::octo_qt::motor_status >
template<>
struct DataType< ::octo_qt::motor_statusRequest>
{
  static const char* value()
  {
    return DataType< ::octo_qt::motor_status >::value();
  }
  static const char* value(const ::octo_qt::motor_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::octo_qt::motor_statusResponse> should match
// service_traits::MD5Sum< ::octo_qt::motor_status >
template<>
struct MD5Sum< ::octo_qt::motor_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::octo_qt::motor_status >::value();
  }
  static const char* value(const ::octo_qt::motor_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::octo_qt::motor_statusResponse> should match
// service_traits::DataType< ::octo_qt::motor_status >
template<>
struct DataType< ::octo_qt::motor_statusResponse>
{
  static const char* value()
  {
    return DataType< ::octo_qt::motor_status >::value();
  }
  static const char* value(const ::octo_qt::motor_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OCTO_QT_MESSAGE_MOTOR_STATUS_H
