// Generated by gencpp from file octo_qt/tool_status.msg
// DO NOT EDIT!


#ifndef OCTO_QT_MESSAGE_TOOL_STATUS_H
#define OCTO_QT_MESSAGE_TOOL_STATUS_H

#include <ros/service_traits.h>


#include <octo_qt/tool_statusRequest.h>
#include <octo_qt/tool_statusResponse.h>


namespace octo_qt
{

struct tool_status
{

typedef tool_statusRequest Request;
typedef tool_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct tool_status
} // namespace octo_qt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::octo_qt::tool_status > {
  static const char* value()
  {
    return "a8968f0be53ac94e5ab8ee2dc4ff5b1c";
  }

  static const char* value(const ::octo_qt::tool_status&) { return value(); }
};

template<>
struct DataType< ::octo_qt::tool_status > {
  static const char* value()
  {
    return "octo_qt/tool_status";
  }

  static const char* value(const ::octo_qt::tool_status&) { return value(); }
};


// service_traits::MD5Sum< ::octo_qt::tool_statusRequest> should match
// service_traits::MD5Sum< ::octo_qt::tool_status >
template<>
struct MD5Sum< ::octo_qt::tool_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::octo_qt::tool_status >::value();
  }
  static const char* value(const ::octo_qt::tool_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::octo_qt::tool_statusRequest> should match
// service_traits::DataType< ::octo_qt::tool_status >
template<>
struct DataType< ::octo_qt::tool_statusRequest>
{
  static const char* value()
  {
    return DataType< ::octo_qt::tool_status >::value();
  }
  static const char* value(const ::octo_qt::tool_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::octo_qt::tool_statusResponse> should match
// service_traits::MD5Sum< ::octo_qt::tool_status >
template<>
struct MD5Sum< ::octo_qt::tool_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::octo_qt::tool_status >::value();
  }
  static const char* value(const ::octo_qt::tool_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::octo_qt::tool_statusResponse> should match
// service_traits::DataType< ::octo_qt::tool_status >
template<>
struct DataType< ::octo_qt::tool_statusResponse>
{
  static const char* value()
  {
    return DataType< ::octo_qt::tool_status >::value();
  }
  static const char* value(const ::octo_qt::tool_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OCTO_QT_MESSAGE_TOOL_STATUS_H
