// Generated by gencpp from file octo_qt/tool_statusResponse.msg
// DO NOT EDIT!


#ifndef OCTO_QT_MESSAGE_TOOL_STATUSRESPONSE_H
#define OCTO_QT_MESSAGE_TOOL_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace octo_qt
{
template <class ContainerAllocator>
struct tool_statusResponse_
{
  typedef tool_statusResponse_<ContainerAllocator> Type;

  tool_statusResponse_()
    : response(false)  {
    }
  tool_statusResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::octo_qt::tool_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::octo_qt::tool_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct tool_statusResponse_

typedef ::octo_qt::tool_statusResponse_<std::allocator<void> > tool_statusResponse;

typedef boost::shared_ptr< ::octo_qt::tool_statusResponse > tool_statusResponsePtr;
typedef boost::shared_ptr< ::octo_qt::tool_statusResponse const> tool_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::octo_qt::tool_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::octo_qt::tool_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::octo_qt::tool_statusResponse_<ContainerAllocator1> & lhs, const ::octo_qt::tool_statusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::octo_qt::tool_statusResponse_<ContainerAllocator1> & lhs, const ::octo_qt::tool_statusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace octo_qt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::octo_qt::tool_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::octo_qt::tool_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::octo_qt::tool_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::octo_qt::tool_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::octo_qt::tool_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::octo_qt::tool_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::octo_qt::tool_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::octo_qt::tool_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::octo_qt::tool_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "octo_qt/tool_statusResponse";
  }

  static const char* value(const ::octo_qt::tool_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::octo_qt::tool_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
;
  }

  static const char* value(const ::octo_qt::tool_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::octo_qt::tool_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tool_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::octo_qt::tool_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::octo_qt::tool_statusResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OCTO_QT_MESSAGE_TOOL_STATUSRESPONSE_H
