// Generated by gencpp from file stm_client/tool_status.msg
// DO NOT EDIT!


#ifndef STM_CLIENT_MESSAGE_TOOL_STATUS_H
#define STM_CLIENT_MESSAGE_TOOL_STATUS_H

#include <ros/service_traits.h>


#include <stm_client/tool_statusRequest.h>
#include <stm_client/tool_statusResponse.h>


namespace stm_client
{

struct tool_status
{

typedef tool_statusRequest Request;
typedef tool_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct tool_status
} // namespace stm_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stm_client::tool_status > {
  static const char* value()
  {
    return "a8968f0be53ac94e5ab8ee2dc4ff5b1c";
  }

  static const char* value(const ::stm_client::tool_status&) { return value(); }
};

template<>
struct DataType< ::stm_client::tool_status > {
  static const char* value()
  {
    return "stm_client/tool_status";
  }

  static const char* value(const ::stm_client::tool_status&) { return value(); }
};


// service_traits::MD5Sum< ::stm_client::tool_statusRequest> should match
// service_traits::MD5Sum< ::stm_client::tool_status >
template<>
struct MD5Sum< ::stm_client::tool_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stm_client::tool_status >::value();
  }
  static const char* value(const ::stm_client::tool_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stm_client::tool_statusRequest> should match
// service_traits::DataType< ::stm_client::tool_status >
template<>
struct DataType< ::stm_client::tool_statusRequest>
{
  static const char* value()
  {
    return DataType< ::stm_client::tool_status >::value();
  }
  static const char* value(const ::stm_client::tool_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stm_client::tool_statusResponse> should match
// service_traits::MD5Sum< ::stm_client::tool_status >
template<>
struct MD5Sum< ::stm_client::tool_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stm_client::tool_status >::value();
  }
  static const char* value(const ::stm_client::tool_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stm_client::tool_statusResponse> should match
// service_traits::DataType< ::stm_client::tool_status >
template<>
struct DataType< ::stm_client::tool_statusResponse>
{
  static const char* value()
  {
    return DataType< ::stm_client::tool_status >::value();
  }
  static const char* value(const ::stm_client::tool_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STM_CLIENT_MESSAGE_TOOL_STATUS_H
