// Generated by gencpp from file octo_arm_teleop/GUI_adra_statRequest.msg
// DO NOT EDIT!


#ifndef OCTO_ARM_TELEOP_MESSAGE_GUI_ADRA_STATREQUEST_H
#define OCTO_ARM_TELEOP_MESSAGE_GUI_ADRA_STATREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace octo_arm_teleop
{
template <class ContainerAllocator>
struct GUI_adra_statRequest_
{
  typedef GUI_adra_statRequest_<ContainerAllocator> Type;

  GUI_adra_statRequest_()
    {
    }
  GUI_adra_statRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GUI_adra_statRequest_

typedef ::octo_arm_teleop::GUI_adra_statRequest_<std::allocator<void> > GUI_adra_statRequest;

typedef boost::shared_ptr< ::octo_arm_teleop::GUI_adra_statRequest > GUI_adra_statRequestPtr;
typedef boost::shared_ptr< ::octo_arm_teleop::GUI_adra_statRequest const> GUI_adra_statRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace octo_arm_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "octo_arm_teleop/GUI_adra_statRequest";
  }

  static const char* value(const ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GUI_adra_statRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::octo_arm_teleop::GUI_adra_statRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OCTO_ARM_TELEOP_MESSAGE_GUI_ADRA_STATREQUEST_H
