// Generated by gencpp from file stm_client/atm_arr.msg
// DO NOT EDIT!


#ifndef STM_CLIENT_MESSAGE_ATM_ARR_H
#define STM_CLIENT_MESSAGE_ATM_ARR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stm_client
{
template <class ContainerAllocator>
struct atm_arr_
{
  typedef atm_arr_<ContainerAllocator> Type;

  atm_arr_()
    : data()  {
      data.assign(0.0);
  }
  atm_arr_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0.0);
  }



   typedef boost::array<float, 3>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::stm_client::atm_arr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stm_client::atm_arr_<ContainerAllocator> const> ConstPtr;

}; // struct atm_arr_

typedef ::stm_client::atm_arr_<std::allocator<void> > atm_arr;

typedef boost::shared_ptr< ::stm_client::atm_arr > atm_arrPtr;
typedef boost::shared_ptr< ::stm_client::atm_arr const> atm_arrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stm_client::atm_arr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stm_client::atm_arr_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stm_client::atm_arr_<ContainerAllocator1> & lhs, const ::stm_client::atm_arr_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stm_client::atm_arr_<ContainerAllocator1> & lhs, const ::stm_client::atm_arr_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stm_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stm_client::atm_arr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stm_client::atm_arr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stm_client::atm_arr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stm_client::atm_arr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stm_client::atm_arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stm_client::atm_arr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stm_client::atm_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b97789d46afcb9293725ec7b2cfcf8bb";
  }

  static const char* value(const ::stm_client::atm_arr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb97789d46afcb929ULL;
  static const uint64_t static_value2 = 0x3725ec7b2cfcf8bbULL;
};

template<class ContainerAllocator>
struct DataType< ::stm_client::atm_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stm_client/atm_arr";
  }

  static const char* value(const ::stm_client::atm_arr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stm_client::atm_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] data\n"
;
  }

  static const char* value(const ::stm_client::atm_arr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stm_client::atm_arr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct atm_arr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stm_client::atm_arr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stm_client::atm_arr_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STM_CLIENT_MESSAGE_ATM_ARR_H
