// Generated by gencpp from file stm_client/relay_controlResponse.msg
// DO NOT EDIT!


#ifndef STM_CLIENT_MESSAGE_RELAY_CONTROLRESPONSE_H
#define STM_CLIENT_MESSAGE_RELAY_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stm_client
{
template <class ContainerAllocator>
struct relay_controlResponse_
{
  typedef relay_controlResponse_<ContainerAllocator> Type;

  relay_controlResponse_()
    : response(false)  {
    }
  relay_controlResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::stm_client::relay_controlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stm_client::relay_controlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct relay_controlResponse_

typedef ::stm_client::relay_controlResponse_<std::allocator<void> > relay_controlResponse;

typedef boost::shared_ptr< ::stm_client::relay_controlResponse > relay_controlResponsePtr;
typedef boost::shared_ptr< ::stm_client::relay_controlResponse const> relay_controlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stm_client::relay_controlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stm_client::relay_controlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stm_client::relay_controlResponse_<ContainerAllocator1> & lhs, const ::stm_client::relay_controlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stm_client::relay_controlResponse_<ContainerAllocator1> & lhs, const ::stm_client::relay_controlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stm_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stm_client::relay_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stm_client::relay_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stm_client::relay_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stm_client::relay_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stm_client::relay_controlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stm_client::relay_controlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stm_client::relay_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::stm_client::relay_controlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::stm_client::relay_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stm_client/relay_controlResponse";
  }

  static const char* value(const ::stm_client::relay_controlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stm_client::relay_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
"\n"
;
  }

  static const char* value(const ::stm_client::relay_controlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stm_client::relay_controlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct relay_controlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stm_client::relay_controlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stm_client::relay_controlResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STM_CLIENT_MESSAGE_RELAY_CONTROLRESPONSE_H
